matrix:
  RUST: [stable]

steps:
  test:
    image: rust
    environment: [CARGO_TERM_COLOR=always]
    commands:
      - rustup default $RUST
      - cargo check
      - cargo test
    when:
      event: [push, pull_request, pull_request_closed]
